schemaVersion = 1
id = "@habitat-ai/resource-filesystem"
ownerProject = "@habitat-ai/resource-filesystem"
blueprint = "resource"
blueprintVersion = 3
[roots]
project = "resources/filesystem"
[selections]
