schemaVersion = 1
id = "@habitat-ai/resource-rule-evaluation"
ownerProject = "@habitat-ai/resource-rule-evaluation"
blueprint = "resource"
blueprintVersion = 3

[roots]
project = "resources/rule-evaluation"

[selections]
