schemaVersion = 1
id = "@habitat-ai/resource-versioned-content"
ownerProject = "@habitat-ai/resource-versioned-content"
blueprint = "resource"
blueprintVersion = 3

[roots]
project = "resources/versioned-content"

[selections]
