schemaVersion = 1
id = "@habitat-ai/resource-agent-plugin-package-output"
ownerProject = "@habitat-ai/resource-agent-plugin-package-output"
blueprint = "resource"
blueprintVersion = 2

[roots]
project = "resources/agent-plugin-package-output"

[selections]
