schemaVersion = 1
id = "@habitat-ai/resource-telemetry"
ownerProject = "@habitat-ai/resource-telemetry"
blueprint = "resource"
blueprintVersion = 3

[roots]
project = "resources/telemetry"

[selections]
