/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/exampleTodo/tasks/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a task in the example todo capability */
        post: operations["exampleTodoCreateTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exampleTodo/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task from the example todo capability */
        get: operations["exampleTodoGetTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exampleTodoCreateTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Human-readable task title. */
                    title: string;
                    /** @description Optional longer details for the task. */
                    description?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Stable unique identifier for the task.
                         */
                        id: string;
                        /** @description Workspace scope that owns this task record. */
                        workspaceId: string;
                        /** @description Primary task title. */
                        title: string;
                        /** @description Optional task description value. */
                        description: string | null;
                        /** @description Completion status of the task. */
                        completed: boolean;
                        /**
                         * Format: date-time
                         * @description ISO timestamp when the task was created.
                         */
                        createdAt: string;
                        /**
                         * Format: date-time
                         * @description ISO timestamp when the task was last updated.
                         */
                        updatedAt: string;
                    };
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        defined: true;
                        /** @constant */
                        code: "INVALID_TASK_TITLE";
                        /** @constant */
                        status: 400;
                        /** @default Invalid task title */
                        message: string;
                        /** @description Context describing why the task title was rejected. */
                        data: {
                            /** @description Raw title value that failed validation or normalization. */
                            title?: string;
                        };
                    } | {
                        /** @constant */
                        defined: false;
                        code: string;
                        status: number;
                        message: string;
                        data?: unknown;
                    };
                };
            };
            /** @description 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        defined: true;
                        /** @constant */
                        code: "READ_ONLY_MODE";
                        /** @constant */
                        status: 409;
                        /** @default Write operations are blocked while read-only mode is enabled */
                        message: string;
                        /** @description Context payload for READ_ONLY_MODE boundary errors. */
                        data: {
                            /** @description Procedure path that was blocked while read-only mode was enabled. */
                            path?: string;
                        };
                    } | {
                        /** @constant */
                        defined: false;
                        code: string;
                        status: number;
                        message: string;
                        data?: unknown;
                    };
                };
            };
        };
    };
    exampleTodoGetTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Stable unique identifier for the task.
                         */
                        id: string;
                        /** @description Workspace scope that owns this task record. */
                        workspaceId: string;
                        /** @description Primary task title. */
                        title: string;
                        /** @description Optional task description value. */
                        description: string | null;
                        /** @description Completion status of the task. */
                        completed: boolean;
                        /**
                         * Format: date-time
                         * @description ISO timestamp when the task was created.
                         */
                        createdAt: string;
                        /**
                         * Format: date-time
                         * @description ISO timestamp when the task was last updated.
                         */
                        updatedAt: string;
                    };
                };
            };
            /** @description 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        defined: true;
                        /** @constant */
                        code: "RESOURCE_NOT_FOUND";
                        /** @constant */
                        status: 404;
                        /** @default Resource not found */
                        message: string;
                        /** @description Context payload for RESOURCE_NOT_FOUND boundary errors. */
                        data: {
                            /** @description Entity name that was not found (for example Task or Tag). */
                            entity?: string;
                            /** @description Identifier associated with the missing entity. */
                            id?: string;
                        };
                    } | {
                        /** @constant */
                        defined: false;
                        code: string;
                        status: number;
                        message: string;
                        data?: unknown;
                    };
                };
            };
        };
    };
}
