/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/coordination/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved coordination workflows */
        get: operations["coordinationListWorkflows"];
        put?: never;
        /** Create or update a coordination workflow */
        post: operations["coordinationSaveWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coordination/workflows/{workflowId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a coordination workflow by id */
        get: operations["coordinationGetWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coordination/workflows/{workflowId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a coordination workflow */
        post: operations["coordinationValidateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coordination/workflows/{workflowId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a workflow run */
        post: operations["coordinationQueueRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coordination/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workflow run status */
        get: operations["coordinationGetRunStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coordination/runs/{runId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workflow run timeline */
        get: operations["coordinationGetRunTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read runtime plugin state */
        get: operations["stateGetRuntimeState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    coordinationListWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workflows: {
                            workflowId: string;
                            version: number;
                            name: string;
                            description?: string;
                            entryDeskId: string;
                            desks: {
                                deskId: string;
                                kind: string;
                                name: string;
                                responsibility: string;
                                domain: string;
                                /** JsonSchemaV1 */
                                inputSchema: Record<string, never>;
                                /** JsonSchemaV1 */
                                outputSchema: Record<string, never>;
                                memoryScope: {
                                    persist: boolean;
                                    ttlSeconds?: number;
                                    namespace?: string;
                                };
                                runtimePolicy?: {
                                    retries?: number;
                                    timeoutSeconds?: number;
                                    priority?: "low" | "normal" | "high";
                                };
                            }[];
                            handoffs: {
                                handoffId: string;
                                fromDeskId: string;
                                toDeskId: string;
                                condition?: string;
                                mappingRefs?: {
                                    [key: string]: string;
                                };
                            }[];
                            observabilityProfile?: "basic" | "full";
                            updatedAt?: string;
                        }[];
                    };
                };
            };
        };
    };
    coordinationSaveWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    workflow: {
                        workflowId: string;
                        version: number;
                        name: string;
                        description?: string;
                        entryDeskId: string;
                        desks: {
                            deskId: string;
                            kind: string;
                            name: string;
                            responsibility: string;
                            domain: string;
                            /** JsonSchemaV1 */
                            inputSchema: Record<string, never>;
                            /** JsonSchemaV1 */
                            outputSchema: Record<string, never>;
                            memoryScope: {
                                persist: boolean;
                                ttlSeconds?: number;
                                namespace?: string;
                            };
                            runtimePolicy?: {
                                retries?: number;
                                timeoutSeconds?: number;
                                priority?: "low" | "normal" | "high";
                            };
                        }[];
                        handoffs: {
                            handoffId: string;
                            fromDeskId: string;
                            toDeskId: string;
                            condition?: string;
                            mappingRefs?: {
                                [key: string]: string;
                            };
                        }[];
                        observabilityProfile?: "basic" | "full";
                        updatedAt?: string;
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workflow: {
                            workflowId: string;
                            version: number;
                            name: string;
                            description?: string;
                            entryDeskId: string;
                            desks: {
                                deskId: string;
                                kind: string;
                                name: string;
                                responsibility: string;
                                domain: string;
                                /** JsonSchemaV1 */
                                inputSchema: Record<string, never>;
                                /** JsonSchemaV1 */
                                outputSchema: Record<string, never>;
                                memoryScope: {
                                    persist: boolean;
                                    ttlSeconds?: number;
                                    namespace?: string;
                                };
                                runtimePolicy?: {
                                    retries?: number;
                                    timeoutSeconds?: number;
                                    priority?: "low" | "normal" | "high";
                                };
                            }[];
                            handoffs: {
                                handoffId: string;
                                fromDeskId: string;
                                toDeskId: string;
                                condition?: string;
                                mappingRefs?: {
                                    [key: string]: string;
                                };
                            }[];
                            observabilityProfile?: "basic" | "full";
                            updatedAt?: string;
                        };
                    };
                };
            };
        };
    };
    coordinationGetWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workflow: {
                            workflowId: string;
                            version: number;
                            name: string;
                            description?: string;
                            entryDeskId: string;
                            desks: {
                                deskId: string;
                                kind: string;
                                name: string;
                                responsibility: string;
                                domain: string;
                                /** JsonSchemaV1 */
                                inputSchema: Record<string, never>;
                                /** JsonSchemaV1 */
                                outputSchema: Record<string, never>;
                                memoryScope: {
                                    persist: boolean;
                                    ttlSeconds?: number;
                                    namespace?: string;
                                };
                                runtimePolicy?: {
                                    retries?: number;
                                    timeoutSeconds?: number;
                                    priority?: "low" | "normal" | "high";
                                };
                            }[];
                            handoffs: {
                                handoffId: string;
                                fromDeskId: string;
                                toDeskId: string;
                                condition?: string;
                                mappingRefs?: {
                                    [key: string]: string;
                                };
                            }[];
                            observabilityProfile?: "basic" | "full";
                            updatedAt?: string;
                        };
                    };
                };
            };
        };
    };
    coordinationValidateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workflowId: string;
                        validation: {
                            ok: boolean;
                            errors: {
                                code: string;
                                message: string;
                                deskId?: string;
                                handoffId?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    coordinationQueueRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    runId?: string;
                    /** JsonValue */
                    input?: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: {
                            runId: string;
                            workflowId: string;
                            workflowVersion: number;
                            status: "queued" | "running" | "completed" | "failed";
                            startedAt: string;
                            finishedAt?: string;
                            /** JsonValue */
                            input?: unknown;
                            /** JsonValue */
                            output?: unknown;
                            error?: string;
                            traceLinks: {
                                provider: "inngest" | "rawr";
                                label: string;
                                url: string;
                            }[];
                        };
                        eventIds: string[];
                    };
                };
            };
        };
    };
    coordinationGetRunStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: {
                            runId: string;
                            workflowId: string;
                            workflowVersion: number;
                            status: "queued" | "running" | "completed" | "failed";
                            startedAt: string;
                            finishedAt?: string;
                            /** JsonValue */
                            input?: unknown;
                            /** JsonValue */
                            output?: unknown;
                            error?: string;
                            traceLinks: {
                                provider: "inngest" | "rawr";
                                label: string;
                                url: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    coordinationGetRunTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId: string;
                        timeline: {
                            eventId: string;
                            runId: string;
                            workflowId: string;
                            deskId?: string;
                            type: "run.started" | "run.completed" | "run.failed" | "desk.started" | "desk.completed" | "desk.failed";
                            ts: string;
                            status: "queued" | "running" | "completed" | "failed";
                            detail?: string;
                            /** JsonValue */
                            input?: unknown;
                            /** JsonValue */
                            output?: unknown;
                        }[];
                    };
                };
            };
        };
    };
    stateGetRuntimeState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        state: {
                            /** @constant */
                            version: 1;
                            plugins: {
                                enabled: string[];
                                disabled?: string[];
                                lastUpdatedAt: string;
                            };
                        };
                    };
                };
            };
        };
    };
}
