import { defineConfig } from "tsdown";

const privateWorkspacePackages = [
  "@habitat-ai/resource-telemetry",
  "@habitat-ai/resource-telemetry/providers/opentelemetry-node",
];

const blueprintIds = [
  "app",
  "package",
  "plugin",
  "plugin-cli-topic",
  "plugin-nx",
  "provider",
  "resource",
  "runtime-bootgraph",
  "runtime-compiler",
  "runtime-definition",
  "runtime-derivation",
  "runtime-harnesses",
  "runtime-mounting",
  "runtime-observation",
  "runtime-process-runtime",
  "runtime-substrate-effect",
  "service",
];

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "app/index": "src/app/index.ts",
    "effect/index": "src/effect/index.ts",
    "effect/context": "src/effect/context.ts",
    "effect/wrap": "src/effect/wrap.ts",
    "execution/index": "src/execution/index.ts",
    "service/index": "src/service/index.ts",
    "service/schema": "src/service/schema.ts",
    "plugins/server/index": "src/plugins/server/index.ts",
    "plugins/server/effect/index": "src/plugins/server/effect/index.ts",
    "plugins/async/index": "src/plugins/async/index.ts",
    "plugins/async/effect/index": "src/plugins/async/effect/index.ts",
    "plugins/web/index": "src/plugins/web/index.ts",
    "plugins/web/effect/index": "src/plugins/web/effect/index.ts",
    "plugins/cli/index": "src/plugins/cli/index.ts",
    "plugins/cli/effect/index": "src/plugins/cli/effect/index.ts",
    "plugins/cli/schema/index": "src/plugins/cli/schema/index.ts",
    "plugins/cli/oclif/index": "src/plugins/cli/oclif/index.ts",
    "plugins/agent/index": "src/plugins/agent/index.ts",
    "plugins/agent/effect/index": "src/plugins/agent/effect/index.ts",
    "plugins/agent/schema/index": "src/plugins/agent/schema/index.ts",
    "plugins/desktop/index": "src/plugins/desktop/index.ts",
    "plugins/desktop/effect/index": "src/plugins/desktop/effect/index.ts",
    "runtime/resources/index": "src/runtime/resources/index.ts",
    "runtime/providers/index": "src/runtime/providers/index.ts",
    "runtime/providers/effect/index": "src/runtime/providers/effect/index.ts",
    "runtime/profiles/index": "src/runtime/profiles/index.ts",
    "runtime/derivation/index": "src/runtime/derivation/index.ts",
    "runtime/harnesses/index": "src/runtime/harnesses/index.ts",
    "runtime/harnesses/elysia": "src/runtime/harnesses/elysia.ts",
    "runtime/harnesses/inngest": "src/runtime/harnesses/inngest.ts",
    "runtime/harnesses/web": "src/runtime/harnesses/web.ts",
    "runtime/observation/index": "src/runtime/observation/index.ts",
    "runtime/schema": "src/runtime/schema.ts",
    telemetry: "src/telemetry.ts",
  },
  outDir: "dist",
  format: "esm",
  platform: "node",
  target: "node24.11.0",
  fixedExtension: false,
  dts: {
    resolver: "tsc",
  },
  deps: {
    alwaysBundle: privateWorkspacePackages,
    onlyImport: [
      "@effect/opentelemetry",
      "@oclif/core",
      "@opentelemetry/api",
      "@opentelemetry/resources",
      "@opentelemetry/semantic-conventions",
      "@orpc/client",
      "@orpc/contract",
      "@orpc/experimental-effect",
      "@orpc/openapi",
      "@orpc/opentelemetry",
      "@orpc/server",
      "@orpc/shared",
      "@standard-schema/spec",
      "effect",
      "elysia",
      "inngest",
      "inngest/bun",
      "inngest/connect",
      "inngest/types",
      "dotenv",
      "rou3",
      "typebox",
    ],
  },
  copy: blueprintIds.map((id) => ({
    from: `../../../.habitat/blueprints/${id}`,
    to: "dist/blueprints",
  })),
});
