export type {
  AppRole,
  HarnessDescriptor,
  HarnessFinding,
  HarnessHealthKind,
  HarnessHealthReport,
  HarnessHealthStatus,
  HarnessMountInput,
  HarnessReportSink,
  NativeHarnessHandle,
  ProcessRuntimeAccess,
  RequiredResourceReadiness,
  RequiredResourceReadinessRecord,
  RuntimeLaunchIdentity,
} from "./harness-descriptor";
