schemaVersion = 1
id = "@rawr/resource-agent-plugin-export-destination"
ownerProject = "@rawr/resource-agent-plugin-export-destination"
blueprint = "resource"
blueprintVersion = 1

[roots]
project = "resources/agent-plugin-export-destination"

[selections]
